# Generated by Django 5.1.7 on 2025-03-07 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0002_adminuser_delete_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kriteria', models.CharField(max_length=255)),
                ('pertanyaan', models.TextField()),
                ('kategori', models.CharField(choices=[('robotik', 'Robotik'), ('coding', 'Coding')], max_length=10)),
                ('mb', models.DecimalField(decimal_places=2, max_digits=5)),
                ('md', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cfrule', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
