# Generated by Django 5.1.7 on 2025-03-08 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0003_kriteria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kelas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kelas', models.CharField(max_length=255)),
            ],
        ),
    ]
