# Generated by Django 5.1.7 on 2025-04-07 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0004_kelas'),
    ]

    operations = [
        migrations.AddField(
            model_name='kriteria',
            name='kelas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adm.kelas'),
        ),
        migrations.AlterField(
            model_name='kriteria',
            name='cfrule',
            field=models.DecimalField(decimal_places=1, editable=False, max_digits=5),
        ),
        migrations.AlterField(
            model_name='kriteria',
            name='mb',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
        migrations.AlterField(
            model_name='kriteria',
            name='md',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
    ]
