# Generated by Django 5.1.7 on 2025-03-08 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='minat_awal',
            field=models.CharField(choices=[('robotika', 'Robotika'), ('coding', 'Coding')], default='robotika', max_length=10),
        ),
    ]
