# Generated by Django 5.1.7 on 2025-03-09 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_minat_awal'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='CustomUser',
        ),
    ]
