# Generated by Django 5.1.7 on 2025-04-21 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_hasilcf_user_alter_jawabanuser_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='minat_awal',
        ),
    ]
